# Python exercises

Data Science  
TECNUN - Escuela de Ingeniería  
Universidad de Navarra

- Idoia Ochoa Alvarez: iochoal@unav.es


## 1 - Python basics

1. Even or Odd: Write a program that takes an integer as input and prints whether it is even or odd.

Hint: use the `input()` function.

In [4]:
num = input("Enter a number: ")
num = int(num)
if num % 2 == 0:
    print("Even")
else:
    print("Odd")

Even


2. Fibonacci Sequence: Write a program to print the first 10 numbers of the Fibonacci sequence using a loop.

In [8]:
fibonacci_sequence = [0, 1]
for i in range(2, 10):
    next_number = fibonacci_sequence[i-1] + fibonacci_sequence[i-2]
    fibonacci_sequence.append(next_number)
print(fibonacci_sequence)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


3. Multiplication Table: Write a program that prints the multiplication table for a given number using a loop.

In [10]:
number = input("Enter a number: ")
number = int(number)
multiplication_table = []
for i in range(0, 11):
    multiplication_table.append(number * i)
    print(number, "x", i, "=", number * i)
print("The multiplication table of", number, "is: ", multiplication_table)

9 x 0 = 0
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90
The multiplication table of 9 is:  [0, 9, 18, 27, 36, 45, 54, 63, 72, 81, 90]


4. Sum of List: Write a program that calculates the sum of all numbers in a list.

In [20]:
lista2 = [29,11,2002,2,9,1,1,2,0,0,2]
suma2 = sum(lista2)
print(suma2)

2059


5. List Comprehension: Use list comprehension to create a list of squares for numbers 1 to 10.

In [21]:
list = [1,2,3,4,5,6,7,8,9,10]
squares = [x**2 for x in list]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


6. Count Occurrences: Write a program that counts the occurrences of each character in a string and stores them in a dictionary.

In [23]:
string = "Perro Sanchez hijo de puta"
dictionary = {}

for char in string:
    if char in dictionary:
        dictionary[char] += 1
    else:
        dictionary[char] = 1

print(dictionary)

{'P': 1, 'e': 3, 'r': 2, 'o': 2, ' ': 4, 'S': 1, 'a': 2, 'n': 1, 'c': 1, 'h': 2, 'z': 1, 'i': 1, 'j': 1, 'd': 1, 'p': 1, 'u': 1, 't': 1}


7. Vowel Counter: Write a function that counts the number of vowels in a given string.


In [24]:
vowel_counter = 0
vowels = "aeiouAEIOU"
for char in string:
    if char in vowels:
        vowel_counter += 1
print("Number of vowels in the string:", vowel_counter)

Number of vowels in the string: 9


8. Filter Even Numbers: Use a list comprehension to filter out only the even numbers from a given list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].

In [25]:
list = [1,2,3,4,5,6,7,8,9,10]
evens = [x for x in list if x % 2 == 0]
print(evens)

[2, 4, 6, 8, 10]


## 2 - Numpy

1. i) Create a 1-dimensional NumPy array with values from 0 to 9; ii) Check its shape and data type; iii) Reshape it into a 2x5 matrix.

In [27]:
import numpy as np
array = np.array([0,1,2,3,4,5,6,7,8,9])

In [30]:
print(array.shape)
print(array.dtype)

(10,)
int64


In [36]:
array = array.reshape(2,5)
print(array.shape)
print(array)

(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]


2. Compute the product of the following two matrices.

In [37]:
product = array[0:] * array[1:]
print(product)

[[ 0  6 14 24 36]
 [25 36 49 64 81]]


3. Create a 3x3 matrix with values ranging from 0 to 8.

 Extract the element at the second row and third column.

Slice the first two rows and the first two columns from the 3x3 matrix.

In [61]:
matriz = np.array([(0,1,2),(3,4,5),(6,7,8)])
print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [62]:
element = matriz[1,2]
print(element)

5


In [65]:
f2r = matriz[0:2,:]
f2c = matriz[:,0:2]
print(f2r)
print(f2c)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [3 4]
 [6 7]]


4. Create a 1-dimensional array with 10 random integers between 0 and 100, and then compute the mean, median, and standard deviation.

In [104]:
vector = np.random.randint(0,100,10)
print(vector)
print(vector.mean())
print(np.median(vector))
print(np.std(vector))

[81 63 33 72 56 92 39 39 69 17]
56.1
59.5
22.41182723474371


## 3 - Pandas

In [106]:
import pandas as pd

1. Read the .csv located at 'https://raw.githubusercontent.com/iochoa/ml-datasets/master/diabetes.csv' and convert it to a dataframe.

In [112]:
df = pd.read_csv("https://raw.githubusercontent.com/iochoa/ml-datasets/master/diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1


2. Print the first 6 rows and the last 7 rows

In [121]:
print(df[:6])
print(df[-7:])

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   
5            5      116             74              0        0  25.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
761            9      170             74             31        0  44.0   
762            9       89             6

3. Provide the statistics of column `Glucose` using the function `describe()`

In [124]:
df.Glucose.describe()

count    768.000000
mean     120.894531
std       31.972618
min        0.000000
25%       99.000000
50%      117.000000
75%      140.250000
max      199.000000
Name: Glucose, dtype: float64

4. Check if there are duplicates

In [128]:
df.duplicated().any()

np.False_

5. Extract columns Glucose and BloodPressure and store them in a new dataframe called df_1

In [131]:
df_1 = df[["Glucose", "BloodPressure"]]
df_1

,Glucose,BloodPressure
0,148,72
1,85,66
2,183,64
3,89,66
4,137,40
...,...,...
763,101,76
764,122,70
765,121,72
766,126,60


6. Create a new column with value equal to the result of adding the values Glucose + BloodPressure and called it 'G+B'

In [133]:
df_1["G+B"] = df_1.Glucose + df_1.BloodPressure
df_1

C:\Users\enriq\AppData\Local\Temp\ipykernel_33544\175370526.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1["G+B"] = df_1.Glucose + df_1.BloodPressure


,Glucose,BloodPressure,G+B
0,148,72,220
1,85,66,151
2,183,64,247
3,89,66,155
4,137,40,177
...,...,...,...
763,101,76,177
764,122,70,192
765,121,72,193
766,126,60,186


7. Extract rows such that BloodPressure is higher than 70

In [137]:
BP70 = df_1[df_1["BloodPressure"]>70]
BP70

,Glucose,BloodPressure,G+B
0,148,72,220
5,116,74,190
9,125,96,221
10,110,92,202
11,168,74,242
...,...,...,...
758,106,76,182
759,190,92,282
761,170,74,244
763,101,76,177


8. Print only rows 2 and 3

In [140]:
print(BP70.iloc[[1,2]])

   Glucose  BloodPressure  G+B
5      116             74  190
9      125             96  221
